version: '3.8'

services:
  # PostgreSQL Database - Primary persistent storage
  postgres:
    image: postgres:16-alpine
    container_name: unthread-postgres
    environment:
      POSTGRES_DB: unthread_discord_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache - L2 cache and bot operations
  redis-cache:
    image: redis:7-alpine
    container_name: unthread-redis-cache
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Redis Queue - Webhook processing and job queues
  redis-queue:
    image: redis:7-alpine
    container_name: unthread-redis-queue
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy noeviction
    ports:
      - "6380:6379"
    volumes:
      - redis_queue_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Discord Bot Application
  discord-bot:
    build: .
    container_name: unthread-discord-bot
    depends_on:
      postgres:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    environment:
      # Discord Configuration
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      
      # Unthread Configuration
      UNTHREAD_API_KEY: ${UNTHREAD_API_KEY}
      UNTHREAD_SLACK_CHANNEL_ID: ${UNTHREAD_SLACK_CHANNEL_ID}
      UNTHREAD_WEBHOOK_SECRET: ${UNTHREAD_WEBHOOK_SECRET}
      
      # Storage Configuration
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/unthread_discord_bot
      REDIS_CACHE_URL: redis://redis-cache:6379
      REDIS_QUEUE_URL: redis://redis-queue:6379
      
      # Optional Configuration
      FORUM_CHANNEL_IDS: ${FORUM_CHANNEL_IDS:-}
      DEBUG_MODE: ${DEBUG_MODE:-false}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_cache_data:
    driver: local
  redis_queue_data:
    driver: local

networks:
  default:
    name: unthread-network
    driver: bridge